FROM node:18

WORKDIR /usr/src/app

# Copy package.json and lock file from src/foo
COPY src/foo/package*.json ./

RUN npm install

# Copy rest of the Node.js app
COPY src/foo .

EXPOSE 3000

CMD ["node", "app.js"]
